=== kuali-student/ks-final-milestone/1.0.x/ks-cfg-dbs/ks-core-db/src/main/resources/impex/data.dtd
<!ELEMENT dataset (
    KSAP_ATP|
    KSAP_ATP_ATTR|
    KSAP_ATP_DUR_TYPE|
    KSAP_ATP_DUR_TYPE_ATTR|
    KSAP_ATP_SEASONAL_TYPE|
    KSAP_ATP_SEASONAL_TYPE_ATTR|
    KSAP_ATP_TYPE|
    KSAP_ATP_TYPE_ATTR|
    KSAP_DT_RANGE|
    KSAP_DT_RANGE_ATTR|
    KSAP_DT_RANGE_TYPE|
    KSAP_DT_RANGE_TYPE_ATTR|
    KSAP_MLSTN|
    KSAP_MLSTN_ATTR|
    KSAP_MLSTN_TYPE|
    KSAP_MLSTN_TYPE_ATTR|
    KSAP_RICH_TEXT_T|
    KSCO_COMMENT|
    KSCO_COMMENT_ATTR|
    KSCO_COMMENT_TYPE|
    KSCO_COMMENT_TYPE_ATTR|
    KSCO_REFERENCE|
    KSCO_REFERENCE_TYPE|
    KSCO_REFERENCE_TYPE_ATTR|
    KSCO_RICH_TEXT_T|
    KSCO_TAG|
    KSCO_TAG_ATTR|
    KSCO_TAG_TYPE|
    KSCO_TAG_TYPE_ATTR|
    KSDO_DOCUMENT|
    KSDO_DOCUMENT_ATTR|
    KSDO_DOCUMENT_CATEGORY|
    KSDO_DOCUMENT_CATEGORY_ATTR|
    KSDO_DOCUMENT_JN_DOC_CATEGORY|
    KSDO_DOCUMENT_TYPE|
    KSDO_DOCUMENT_TYPE_ATTR|
    KSDO_RICH_TEXT_T|
    KSEM_CTX_ENT|
    KSEM_CTX_META_ENT|
    KSEM_ENUM_META_ENT|
    KSEM_ENUM_VAL_ENT|
    KSEM_ENUM_VAL_FLD_ENT|
    KSMG_MESSAGE|
    KSOR_ORG|
    KSOR_ORG_ATTR|
    KSOR_ORG_HIRCHY|
    KSOR_ORG_HIRCHY_ATTR|
    KSOR_ORG_HIRCHY_JN_ORG_TYPE|
    KSOR_ORG_JN_ORG_PERS_REL_TYPE|
    KSOR_ORG_ORG_RELTN|
    KSOR_ORG_ORG_RELTN_ATTR|
    KSOR_ORG_ORG_RELTN_TYPE|
    KSOR_ORG_ORG_RELTN_TYPE_ATTR|
    KSOR_ORG_PERS_RELTN|
    KSOR_ORG_PERS_RELTN_ATTR|
    KSOR_ORG_PERS_RELTN_TYPE|
    KSOR_ORG_PERS_RELTN_TYPE_ATTR|
    KSOR_ORG_POS_RESTR|
    KSOR_ORG_POS_RESTR_ATTR|
    KSOR_ORG_TYPE|
    KSOR_ORG_TYPE_ATTR|
    KSOR_ORG_TYPE_JN_ORG_PERRL_TYP|
    KSPR_PROPOSAL|
    KSPR_PROPOSAL_ATTR|
    KSPR_PROPOSAL_DOCREL|
    KSPR_PROPOSAL_DOCREL_ATTR|
    KSPR_PROPOSAL_DOCREL_TYPE|
    KSPR_PROPOSAL_DOCREL_TYPE_ATTR|
    KSPR_PROPOSAL_JN_ORG|
    KSPR_PROPOSAL_JN_PERSON|
    KSPR_PROPOSAL_JN_REFERENCE|
    KSPR_PROPOSAL_REFERENCE|
    KSPR_PROPOSAL_REFTYPE|
    KSPR_PROPOSAL_REFTYPE_ATTR|
    KSPR_PROPOSAL_TYPE|
    KSPR_PROPOSAL_TYPE_ATTR|
    KSPR_RICH_TEXT_T)*>
<!ELEMENT KSAP_ATP EMPTY>
<!ATTLIST KSAP_ATP
    ID CDATA #IMPLIED
    CREATEID CDATA #IMPLIED
    CREATETIME CDATA #IMPLIED
    UPDATEID CDATA #IMPLIED
    UPDATETIME CDATA #IMPLIED
    VERSIONIND CDATA #REQUIRED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
    STATE CDATA #IMPLIED
    RT_DESCR_ID CDATA #IMPLIED
    TYPE CDATA #IMPLIED
>

<!ELEMENT KSAP_ATP_ATTR EMPTY>
<!ATTLIST KSAP_ATP_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSAP_ATP_DUR_TYPE EMPTY>
<!ATTLIST KSAP_ATP_DUR_TYPE
    TYPE_KEY CDATA #IMPLIED
    TYPE_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT KSAP_ATP_DUR_TYPE_ATTR EMPTY>
<!ATTLIST KSAP_ATP_DUR_TYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSAP_ATP_SEASONAL_TYPE EMPTY>
<!ATTLIST KSAP_ATP_SEASONAL_TYPE
    TYPE_KEY CDATA #IMPLIED
    TYPE_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT KSAP_ATP_SEASONAL_TYPE_ATTR EMPTY>
<!ATTLIST KSAP_ATP_SEASONAL_TYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSAP_ATP_TYPE EMPTY>
<!ATTLIST KSAP_ATP_TYPE
    TYPE_KEY CDATA #IMPLIED
    TYPE_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
    DUR_TYPE CDATA #IMPLIED
    SEASONAL_TYPE CDATA #IMPLIED
>

<!ELEMENT KSAP_ATP_TYPE_ATTR EMPTY>
<!ATTLIST KSAP_ATP_TYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSAP_DT_RANGE EMPTY>
<!ATTLIST KSAP_DT_RANGE
    DATERANGE_KEY CDATA #IMPLIED
    CREATEID CDATA #IMPLIED
    CREATETIME CDATA #IMPLIED
    UPDATEID CDATA #IMPLIED
    UPDATETIME CDATA #IMPLIED
    VERSIONIND CDATA #REQUIRED
    END_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
    START_DT CDATA #IMPLIED
    STATE CDATA #IMPLIED
    ATP_ID CDATA #IMPLIED
    RT_DESCR_ID CDATA #IMPLIED
    DT_RANGE_TYPE_ID CDATA #IMPLIED
>

<!ELEMENT KSAP_DT_RANGE_ATTR EMPTY>
<!ATTLIST KSAP_DT_RANGE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSAP_DT_RANGE_TYPE EMPTY>
<!ATTLIST KSAP_DT_RANGE_TYPE
    TYPE_KEY CDATA #IMPLIED
    TYPE_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT KSAP_DT_RANGE_TYPE_ATTR EMPTY>
<!ATTLIST KSAP_DT_RANGE_TYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSAP_MLSTN EMPTY>
<!ATTLIST KSAP_MLSTN
    ID CDATA #IMPLIED
    CREATEID CDATA #IMPLIED
    CREATETIME CDATA #IMPLIED
    UPDATEID CDATA #IMPLIED
    UPDATETIME CDATA #IMPLIED
    VERSIONIND CDATA #REQUIRED
    MLSTN_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
    STATE CDATA #IMPLIED
    ATP_ID CDATA #IMPLIED
    RT_DESCR_ID CDATA #IMPLIED
    MLSTN_TYPE_ID CDATA #IMPLIED
>

<!ELEMENT KSAP_MLSTN_ATTR EMPTY>
<!ATTLIST KSAP_MLSTN_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSAP_MLSTN_TYPE EMPTY>
<!ATTLIST KSAP_MLSTN_TYPE
    TYPE_KEY CDATA #IMPLIED
    TYPE_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT KSAP_MLSTN_TYPE_ATTR EMPTY>
<!ATTLIST KSAP_MLSTN_TYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSAP_RICH_TEXT_T EMPTY>
<!ATTLIST KSAP_RICH_TEXT_T
    ID CDATA #IMPLIED
    FORMATTED CDATA #IMPLIED
    PLAIN CDATA #IMPLIED
>

<!ELEMENT KSCO_COMMENT EMPTY>
<!ATTLIST KSCO_COMMENT
    ID CDATA #IMPLIED
    CREATEID CDATA #IMPLIED
    CREATETIME CDATA #IMPLIED
    UPDATEID CDATA #IMPLIED
    UPDATETIME CDATA #IMPLIED
    VERSIONIND CDATA #REQUIRED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    STATE CDATA #IMPLIED
    RT_DESCR_ID CDATA #IMPLIED
    REFERENCE CDATA #IMPLIED
    TYPE CDATA #IMPLIED
>

<!ELEMENT KSCO_COMMENT_ATTR EMPTY>
<!ATTLIST KSCO_COMMENT_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSCO_COMMENT_TYPE EMPTY>
<!ATTLIST KSCO_COMMENT_TYPE
    TYPE_KEY CDATA #IMPLIED
    TYPE_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT KSCO_COMMENT_TYPE_ATTR EMPTY>
<!ATTLIST KSCO_COMMENT_TYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSCO_REFERENCE EMPTY>
<!ATTLIST KSCO_REFERENCE
    ID CDATA #IMPLIED
    REFERENCE_ID CDATA #IMPLIED
    REFERENCE_TYPE CDATA #IMPLIED
>

<!ELEMENT KSCO_REFERENCE_TYPE EMPTY>
<!ATTLIST KSCO_REFERENCE_TYPE
    TYPE_KEY CDATA #IMPLIED
    TYPE_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT KSCO_REFERENCE_TYPE_ATTR EMPTY>
<!ATTLIST KSCO_REFERENCE_TYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSCO_RICH_TEXT_T EMPTY>
<!ATTLIST KSCO_RICH_TEXT_T
    ID CDATA #IMPLIED
    FORMATTED CDATA #IMPLIED
    PLAIN CDATA #IMPLIED
>

<!ELEMENT KSCO_TAG EMPTY>
<!ATTLIST KSCO_TAG
    ID CDATA #IMPLIED
    CREATEID CDATA #IMPLIED
    CREATETIME CDATA #IMPLIED
    UPDATEID CDATA #IMPLIED
    UPDATETIME CDATA #IMPLIED
    VERSIONIND CDATA #REQUIRED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME_SPACE CDATA #IMPLIED
    PREDICATE CDATA #IMPLIED
    STATE CDATA #IMPLIED
    VAL CDATA #IMPLIED
    REFERENCE CDATA #IMPLIED
    TYPE CDATA #IMPLIED
>

<!ELEMENT KSCO_TAG_ATTR EMPTY>
<!ATTLIST KSCO_TAG_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSCO_TAG_TYPE EMPTY>
<!ATTLIST KSCO_TAG_TYPE
    TYPE_KEY CDATA #IMPLIED
    TYPE_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT KSCO_TAG_TYPE_ATTR EMPTY>
<!ATTLIST KSCO_TAG_TYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSDO_DOCUMENT EMPTY>
<!ATTLIST KSDO_DOCUMENT
    DOC_ID CDATA #IMPLIED
    CREATEID CDATA #IMPLIED
    CREATETIME CDATA #IMPLIED
    UPDATEID CDATA #IMPLIED
    UPDATETIME CDATA #IMPLIED
    VERSIONIND CDATA #REQUIRED
    DOCUMENT CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    FILE_NAME CDATA #IMPLIED
    NAME CDATA #IMPLIED
    STATE CDATA #IMPLIED
    RT_DESCR_ID CDATA #IMPLIED
    TYPE CDATA #IMPLIED
>

<!ELEMENT KSDO_DOCUMENT_ATTR EMPTY>
<!ATTLIST KSDO_DOCUMENT_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSDO_DOCUMENT_CATEGORY EMPTY>
<!ATTLIST KSDO_DOCUMENT_CATEGORY
    CATEGORY_ID CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
    RT_DESCR_ID CDATA #IMPLIED
>

<!ELEMENT KSDO_DOCUMENT_CATEGORY_ATTR EMPTY>
<!ATTLIST KSDO_DOCUMENT_CATEGORY_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSDO_DOCUMENT_JN_DOC_CATEGORY EMPTY>
<!ATTLIST KSDO_DOCUMENT_JN_DOC_CATEGORY
    DOC_ID CDATA #REQUIRED
    CATEGORY_ID CDATA #REQUIRED
>

<!ELEMENT KSDO_DOCUMENT_TYPE EMPTY>
<!ATTLIST KSDO_DOCUMENT_TYPE
    TYPE_KEY CDATA #IMPLIED
    TYPE_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT KSDO_DOCUMENT_TYPE_ATTR EMPTY>
<!ATTLIST KSDO_DOCUMENT_TYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSDO_RICH_TEXT_T EMPTY>
<!ATTLIST KSDO_RICH_TEXT_T
    ID CDATA #IMPLIED
    FORMATTED CDATA #IMPLIED
    PLAIN CDATA #IMPLIED
>

<!ELEMENT KSEM_CTX_ENT EMPTY>
<!ATTLIST KSEM_CTX_ENT
    ID CDATA #IMPLIED
    CTX_KEY CDATA #IMPLIED
    CTX_VAL CDATA #IMPLIED
    ENUM_VAL_ENT_ID CDATA #IMPLIED
>

<!ELEMENT KSEM_CTX_META_ENT EMPTY>
<!ATTLIST KSEM_CTX_META_ENT
    ID CDATA #IMPLIED
    DATA_TYPE CDATA #IMPLIED
    ENUM_KEY CDATA #IMPLIED
    MAX_LGTH CDATA #IMPLIED
    MAX_OCCRS CDATA #IMPLIED
    MIN_LGTH CDATA #IMPLIED
    MIN_OCCRS CDATA #IMPLIED
    TYPE CDATA #IMPLIED
>

<!ELEMENT KSEM_ENUM_META_ENT EMPTY>
<!ATTLIST KSEM_ENUM_META_ENT
    ID CDATA #IMPLIED
    ENUM_KEY CDATA #IMPLIED
    ENUM_META_KEY_DESC CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT KSEM_ENUM_VAL_ENT EMPTY>
<!ATTLIST KSEM_ENUM_VAL_ENT
    ID CDATA #IMPLIED
    ABBREV_VAL CDATA #IMPLIED
    CD CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    ENUM_KEY CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    SORT_KEY CDATA #IMPLIED
    VAL CDATA #IMPLIED
>

<!ELEMENT KSEM_ENUM_VAL_FLD_ENT EMPTY>
<!ATTLIST KSEM_ENUM_VAL_FLD_ENT
    ID CDATA #IMPLIED
    DATA_TYPE CDATA #IMPLIED
    FLD_KEY CDATA #IMPLIED
    INVLD_CHARS CDATA #IMPLIED
    MAX_LGTH CDATA #IMPLIED
    MAX_OCCRS CDATA #IMPLIED
    MAX_VAL CDATA #IMPLIED
    MIN_LGTH CDATA #IMPLIED
    MIN_OCCRS CDATA #IMPLIED
    MIN_VAL CDATA #IMPLIED
    VALID_CHARS CDATA #IMPLIED
    ENUM_META_ENT_ID CDATA #IMPLIED
>

<!ELEMENT KSMG_MESSAGE EMPTY>
<!ATTLIST KSMG_MESSAGE
    DATABASEID CDATA #IMPLIED
    GROUPNAME CDATA #IMPLIED
    ID CDATA #IMPLIED
    LOCALE CDATA #IMPLIED
    VALUE CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG EMPTY>
<!ATTLIST KSOR_ORG
    ID CDATA #IMPLIED
    CREATEID CDATA #IMPLIED
    CREATETIME CDATA #IMPLIED
    UPDATEID CDATA #IMPLIED
    UPDATETIME CDATA #IMPLIED
    VERSIONIND CDATA #REQUIRED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    LNG_DESCR CDATA #IMPLIED
    LNG_NAME CDATA #IMPLIED
    SHRT_DESCR CDATA #IMPLIED
    SHRT_NAME CDATA #IMPLIED
    ST CDATA #IMPLIED
    TYPE CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_ATTR EMPTY>
<!ATTLIST KSOR_ORG_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_HIRCHY EMPTY>
<!ATTLIST KSOR_ORG_HIRCHY
    ID CDATA #IMPLIED
    DESCR CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
    ROOT_ORG CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_HIRCHY_ATTR EMPTY>
<!ATTLIST KSOR_ORG_HIRCHY_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_HIRCHY_JN_ORG_TYPE EMPTY>
<!ATTLIST KSOR_ORG_HIRCHY_JN_ORG_TYPE
    ORG_HIRCHY_ID CDATA #REQUIRED
    ORG_TYPE_ID CDATA #REQUIRED
>

<!ELEMENT KSOR_ORG_JN_ORG_PERS_REL_TYPE EMPTY>
<!ATTLIST KSOR_ORG_JN_ORG_PERS_REL_TYPE
    ORG_ID CDATA #REQUIRED
    ORG_PERS_RELTN_TYPE_ID CDATA #REQUIRED
>

<!ELEMENT KSOR_ORG_ORG_RELTN EMPTY>
<!ATTLIST KSOR_ORG_ORG_RELTN
    ID CDATA #IMPLIED
    CREATEID CDATA #IMPLIED
    CREATETIME CDATA #IMPLIED
    UPDATEID CDATA #IMPLIED
    UPDATETIME CDATA #IMPLIED
    VERSIONIND CDATA #REQUIRED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    ST CDATA #IMPLIED
    ORG CDATA #IMPLIED
    RELATED_ORG CDATA #IMPLIED
    TYPE CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_ORG_RELTN_ATTR EMPTY>
<!ATTLIST KSOR_ORG_ORG_RELTN_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_ORG_RELTN_TYPE EMPTY>
<!ATTLIST KSOR_ORG_ORG_RELTN_TYPE
    TYPE_KEY CDATA #IMPLIED
    TYPE_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
    REV_DESCR CDATA #IMPLIED
    REV_NAME CDATA #IMPLIED
    ORG_HIRCHY CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_ORG_RELTN_TYPE_ATTR EMPTY>
<!ATTLIST KSOR_ORG_ORG_RELTN_TYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_PERS_RELTN EMPTY>
<!ATTLIST KSOR_ORG_PERS_RELTN
    ID CDATA #IMPLIED
    CREATEID CDATA #IMPLIED
    CREATETIME CDATA #IMPLIED
    UPDATEID CDATA #IMPLIED
    UPDATETIME CDATA #IMPLIED
    VERSIONIND CDATA #REQUIRED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    PERS_ID CDATA #IMPLIED
    ST CDATA #IMPLIED
    ORG CDATA #IMPLIED
    ORG_PERS_RELTN_TYPE CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_PERS_RELTN_ATTR EMPTY>
<!ATTLIST KSOR_ORG_PERS_RELTN_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_PERS_RELTN_TYPE EMPTY>
<!ATTLIST KSOR_ORG_PERS_RELTN_TYPE
    TYPE_KEY CDATA #IMPLIED
    TYPE_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_PERS_RELTN_TYPE_ATTR EMPTY>
<!ATTLIST KSOR_ORG_PERS_RELTN_TYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_POS_RESTR EMPTY>
<!ATTLIST KSOR_ORG_POS_RESTR
    ID CDATA #IMPLIED
    CREATEID CDATA #IMPLIED
    CREATETIME CDATA #IMPLIED
    UPDATEID CDATA #IMPLIED
    UPDATETIME CDATA #IMPLIED
    VERSIONIND CDATA #REQUIRED
    DESCR CDATA #IMPLIED
    MAX_NUM_RELTN CDATA #IMPLIED
    MIN_NUM_RELTN CDATA #IMPLIED
    ATPDURATIONTYPEKEY CDATA #IMPLIED
    TIMEQUANTITY CDATA #IMPLIED
    TTL CDATA #IMPLIED
    ORG CDATA #IMPLIED
    PERS_RELTN_TYPE CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_POS_RESTR_ATTR EMPTY>
<!ATTLIST KSOR_ORG_POS_RESTR_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_TYPE EMPTY>
<!ATTLIST KSOR_ORG_TYPE
    TYPE_KEY CDATA #IMPLIED
    TYPE_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_TYPE_ATTR EMPTY>
<!ATTLIST KSOR_ORG_TYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSOR_ORG_TYPE_JN_ORG_PERRL_TYP EMPTY>
<!ATTLIST KSOR_ORG_TYPE_JN_ORG_PERRL_TYP
    ORG_TYPE_ID CDATA #REQUIRED
    ORG_PERS_RELTN_TYPE_ID CDATA #REQUIRED
>

<!ELEMENT KSPR_PROPOSAL EMPTY>
<!ATTLIST KSPR_PROPOSAL
    PROPOSAL_ID CDATA #IMPLIED
    CREATEID CDATA #IMPLIED
    CREATETIME CDATA #IMPLIED
    UPDATEID CDATA #IMPLIED
    UPDATETIME CDATA #IMPLIED
    VERSIONIND CDATA #REQUIRED
    DETAIL_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
    RATIONALE CDATA #IMPLIED
    STATE CDATA #IMPLIED
    TYPE CDATA #IMPLIED
>

<!ELEMENT KSPR_PROPOSAL_ATTR EMPTY>
<!ATTLIST KSPR_PROPOSAL_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSPR_PROPOSAL_DOCREL EMPTY>
<!ATTLIST KSPR_PROPOSAL_DOCREL
    DOCREL_ID CDATA #IMPLIED
    CREATEID CDATA #IMPLIED
    CREATETIME CDATA #IMPLIED
    UPDATEID CDATA #IMPLIED
    UPDATETIME CDATA #IMPLIED
    VERSIONIND CDATA #REQUIRED
    DOCUMENT_ID CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    STATE CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    RT_DESCR_ID CDATA #IMPLIED
    PROPOSAL_ID CDATA #IMPLIED
    TYPE CDATA #IMPLIED
>

<!ELEMENT KSPR_PROPOSAL_DOCREL_ATTR EMPTY>
<!ATTLIST KSPR_PROPOSAL_DOCREL_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSPR_PROPOSAL_DOCREL_TYPE EMPTY>
<!ATTLIST KSPR_PROPOSAL_DOCREL_TYPE
    ID CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT KSPR_PROPOSAL_DOCREL_TYPE_ATTR EMPTY>
<!ATTLIST KSPR_PROPOSAL_DOCREL_TYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSPR_PROPOSAL_JN_ORG EMPTY>
<!ATTLIST KSPR_PROPOSAL_JN_ORG
    ORGREF_ID CDATA #IMPLIED
    ORG_ID CDATA #IMPLIED
    PROPOSAL_ID CDATA #IMPLIED
>

<!ELEMENT KSPR_PROPOSAL_JN_PERSON EMPTY>
<!ATTLIST KSPR_PROPOSAL_JN_PERSON
    ID CDATA #IMPLIED
    PERSONREF_ID CDATA #IMPLIED
    PROPOSAL_ID CDATA #IMPLIED
>

<!ELEMENT KSPR_PROPOSAL_JN_REFERENCE EMPTY>
<!ATTLIST KSPR_PROPOSAL_JN_REFERENCE
    PROPOSAL_ID CDATA #REQUIRED
    REFERENCE_ID CDATA #REQUIRED
>

<!ELEMENT KSPR_PROPOSAL_REFERENCE EMPTY>
<!ATTLIST KSPR_PROPOSAL_REFERENCE
    REFERENCE_ID CDATA #IMPLIED
    OBJECT_REFERENCE_ID CDATA #IMPLIED
    TYPE CDATA #IMPLIED
>

<!ELEMENT KSPR_PROPOSAL_REFTYPE EMPTY>
<!ATTLIST KSPR_PROPOSAL_REFTYPE
    TYPE_KEY CDATA #IMPLIED
    TYPE_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT KSPR_PROPOSAL_REFTYPE_ATTR EMPTY>
<!ATTLIST KSPR_PROPOSAL_REFTYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSPR_PROPOSAL_TYPE EMPTY>
<!ATTLIST KSPR_PROPOSAL_TYPE
    TYPE_KEY CDATA #IMPLIED
    TYPE_DESC CDATA #IMPLIED
    EFF_DT CDATA #IMPLIED
    EXPIR_DT CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT KSPR_PROPOSAL_TYPE_ATTR EMPTY>
<!ATTLIST KSPR_PROPOSAL_TYPE_ATTR
    ID CDATA #IMPLIED
    ATTR_NAME CDATA #IMPLIED
    ATTR_VALUE CDATA #IMPLIED
    OWNER CDATA #IMPLIED
>

<!ELEMENT KSPR_RICH_TEXT_T EMPTY>
<!ATTLIST KSPR_RICH_TEXT_T
    ID CDATA #IMPLIED
    FORMATTED CDATA #IMPLIED
    PLAIN CDATA #IMPLIED
>

=== kuali-student/ks-final-milestone/ks-cfg-dbs/ks-embedded-db/src/main/impex/KSMG_MESSAGE.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "data.dtd">
<!--  Auto-generated by the Maven Impex Plugin -->
<dataset>
    <KSMG_MESSAGE GRP_NAME="common"
        ID="0031def9-fbd9-4a08-a2d9-33c06f141a91" LOCALE="es"
        MSG_ID="cancel" MSG_VALUE="Cancelar"
        OBJ_ID="d8f61adb-131f-4a0b-99c6-9dafca6c8980" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="003f14ee-493e-4ca5-805a-63d656fe6d68" LOCALE="en"
        MSG_ID="cluShortTitle-instruct"
        MSG_VALUE="This is the truncated title that will appear on the printed transcript."
        OBJ_ID="5caab387-d900-411e-b812-d9e2e9eed2aa" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="00657da2-533c-4845-9d9d-d4545719dc8e" LOCALE="en"
        MSG_ID="cluFullView" MSG_VALUE="Proposal Details"
        OBJ_ID="2c8b4357-5511-4490-9fda-11154e3b890d" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="common"
        ID="0091e136-aaa0-4cf7-b1ad-27ef1a87777c" LOCALE="en"
        MSG_ID="search" MSG_VALUE="Search"
        OBJ_ID="c48ec3d0-62c7-45c0-8bbf-038def1946a7" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="0282bba0-e111-11df-85ca-0800200c9a66" LOCALE="en"
        MSG_ID="cluActionsLabel" MSG_VALUE="Course Actions" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="03287fa3-6c4f-41d8-a3d6-ef50b7ec4d26" LOCALE="es"
        MSG_ID="cluCurriculumOversight"
        MSG_VALUE="Descuido del plan de estudios"
        OBJ_ID="9982fee2-7e4b-41d5-bf14-997b014f33d7" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="03579b0c-7ba6-470b-b3e6-2338bbadae7f" LOCALE="en"
        MSG_ID="toolsDesc"
        MSG_VALUE="Support tools for courses and programs."
        OBJ_ID="b208352f-8795-4874-9c81-75e2690afe72" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="035d108d-8c02-482f-add1-eb26a6754eb1" LOCALE="en"
        MSG_ID="cluClassSize-help"
        MSG_VALUE="This does not have to be exact - it will be used as an estimate for evaluation purposes only."
        OBJ_ID="f1ba4f89-2dd1-4696-b16c-b3b151a02114" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="org"
        ID="03ed7448-f40e-4939-8f9d-50a95d1dba64" LOCALE="en"
        MSG_ID="orgName" MSG_VALUE="Name"
        OBJ_ID="a02eeadb-a92f-4db0-9ef6-0f4ff64459e1" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="042239aa-679f-42f7-a42d-88637a32e15c" LOCALE="en"
        MSG_ID="selectByProposalTitle"
        MSG_VALUE="Select by Proposal Title"
        OBJ_ID="7b3eba16-eeaf-442e-b1f4-a316742f57f8" VER_NBR="12"/>
    <KSMG_MESSAGE GRP_NAME="org"
        ID="0457d5e4-362d-4b42-a3b9-6dcb4aa5ed86" LOCALE="en"
        MSG_ID="orgMembersTablePoistionName" MSG_VALUE="Position Name"
        OBJ_ID="468f5a19-7209-4146-9099-48d961d653f6" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="common"
        ID="04dd1dfd-bd1b-403f-94ce-671ab72d952e" LOCALE="en"
        MSG_ID="wfEnroute" MSG_VALUE="Enroute"
        OBJ_ID="1a55bd1d-a6e0-44c9-b613-f5b605bbf10c" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="common"
        ID="04ead193-9061-4a94-b004-9b87042ce6d1" LOCALE="en"
        MSG_ID="advSearch" MSG_VALUE="Advanced Search"
        OBJ_ID="6334ccbd-55f1-48cb-90e9-bcb137a462a9" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="org"
        ID="050beabf-e5be-4595-b459-58045e043698" LOCALE="en"
        MSG_ID="orgOrgRelationNote" MSG_VALUE="Note"
        OBJ_ID="2565b69b-a30b-4c09-aef7-e3c51a71f38e" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="055ea5fb-d3d0-4f71-9128-d857d8db73a5" LOCALE="en"
        MSG_ID="cluLearningResultOutcomes" MSG_VALUE="Outcomes"
        OBJ_ID="f9e29f43-0644-4d40-978f-374d0b0f7c1a" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="065ba09a-770a-4ff8-86b1-30eccd9deed0" LOCALE="en"
        MSG_ID="cluFeeDescription" MSG_VALUE="Fee Description"
        OBJ_ID="ea6b0496-b788-418e-ad7d-d007848a25bf" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="0667cd05-697a-4480-ade3-61d113258d3c" LOCALE="en"
        MSG_ID="cluCourseInformation" MSG_VALUE="Course Information"
        OBJ_ID="b103f2cb-3faf-4987-b41c-05423724fdcc" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="org"
        ID="06cc5169-b71f-43a7-84d7-601bf7e4c301" LOCALE="en"
        MSG_ID="orgPositionTablePositionName" MSG_VALUE="Position Name"
        OBJ_ID="f0b6b6e3-d637-4331-b65c-d93b88e3c888" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="073eb280-e110-11df-85ca-0800200c9a66" LOCALE="en"
        MSG_ID="cluModifyItem" MSG_VALUE="Propose Course Modification" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="075adf49-5105-4d9d-a5cd-dd2877b6e21d" LOCALE="es"
        MSG_ID="cluDescription" MSG_VALUE="Descripci?n de curso"
        OBJ_ID="b60c2c9b-c705-419b-83f8-423fc882cdd8" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="common"
        ID="07875f10-c109-424e-80f5-95c83a55fe88" LOCALE="en"
        MSG_ID="wrapperPanelLogout" MSG_VALUE="Logout"
        OBJ_ID="6c2c329e-aaec-45df-a78f-bcef51e29c92" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="common"
        ID="07eb91eb-75f8-4d8c-9867-a9366ebd49ca" LOCALE="en"
        MSG_ID="kuali.lu.type.CreditCourse.draft" MSG_VALUE="Proposal"
        OBJ_ID="f0a0d755-59dd-4aec-9334-9105069cbb0a" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="validation"
        ID="082a5389-2135-486d-805a-62a3fd2e9952" LOCALE="en"
        MSG_ID="validation.revenueTotal"
        MSG_VALUE="Sum of percentages from all the revenue organizations should be 100."
        OBJ_ID="73f2a5d6-2a6f-49f1-8d2b-c9ccd9ea127b" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="0abc9368-f7fe-4ce8-bd10-39a96258fd1d" LOCALE="en"
        MSG_ID="createCourseSubTitle-help"
        MSG_VALUE="&lt;p>If you are looking to copy a particular course or proposal but cannot find it using the fields here, click Cancel and use either the Course Catalog or Course Search to find it.&lt;/p>"
        OBJ_ID="c2b76ae1-280b-4835-ba77-21e0126a3c04" VER_NBR="12"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="0ae67afa-55e2-4b82-b7c5-ccf0b245ef4c" LOCALE="es"
        MSG_ID="cluCourseRestrictions"
        MSG_VALUE="Restricciones del curso"
        OBJ_ID="ec9f580f-dfd9-4763-bdd5-8001d6316b08" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="validation"
        ID="0b46a024-6fce-42b4-9dab-c1290c186a18" LOCALE="en"
        MSG_ID="validation.expenditureTotal"
        MSG_VALUE="Sum of percentages from all the expenditure organizations should be 100."
        OBJ_ID="1526f910-2a5c-4c8f-9968-c1d98b7052da" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="program"
        ID="0ba35908-4772-45f3-a2d9-86b895b8dc9f" LOCALE="en"
        MSG_ID="minCredits" MSG_VALUE="Minimum expected credits"
        OBJ_ID="e647efdf-52be-410b-bd80-b921bfaa4ed6" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="0cac93c8-a3c6-46b4-86fb-f0b52071a5e2" LOCALE="en"
        MSG_ID="cluFormats-instruct"
        MSG_VALUE="Each course format can consist of any number of activities, and you may have more than one course format for this &lt;br/>course."
        OBJ_ID="9829ee2d-9928-4afb-9d53-e66183ffa6c9" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="org"
        ID="0cde2b8a-1758-4c18-8276-3d6283b571b5" LOCALE="en"
        MSG_ID="orgPositionRelationSection" MSG_VALUE="Positions"
        OBJ_ID="63b2828a-5a0f-4cd1-9a5f-437ebb5ebae2" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="0cff9a7f-48dc-4066-b632-2d1cbb0ff009" LOCALE="en"
        MSG_ID="cluLabFee" MSG_VALUE="Lab Fee"
        OBJ_ID="9d2f9a3a-b91d-4e29-8241-8e461d44761f" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="common"
        ID="0e41fb12-3dd6-4d22-93d3-2c30b18a140e" LOCALE="en"
        MSG_ID="wfApproved" MSG_VALUE="Approved"
        OBJ_ID="46814f1b-30fa-412f-abee-bec04ea05687" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="common"
        ID="0ec4a44f-0e06-4b64-acea-d268bed22db7" LOCALE="en"
        MSG_ID="required" MSG_VALUE="Required"
        OBJ_ID="4ec7d246-1588-4728-8ae1-dc0a5466be28" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="org"
        ID="0f15b565-3e70-4d1d-9955-0de63bcb7604" LOCALE="en"
        MSG_ID="orgTitleOrg" MSG_VALUE="Organization Management"
        OBJ_ID="b48ae828-b88f-4305-b378-9f831c884135" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="0f17f62a-1f22-4852-aa90-a31be1d8cde2" LOCALE="en"
        MSG_ID="cluCoRequisites" MSG_VALUE="Co-Requisites"
        OBJ_ID="fe756114-08d8-47a8-a1b3-480353979dd4" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="program"
        ID="0f3e3831-23f6-4a77-a50b-5176b16010a9" LOCALE="en"
        MSG_ID="maxCredits-watermark" MSG_VALUE="e.g.: 60"
        OBJ_ID="edb7eedd-cd93-4cc5-b30d-7bb947a5e076" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="0f5badac-1fd9-4105-8f77-b258cce23408" LOCALE="en"
        MSG_ID="cluCourseFormatsDurationType" MSG_VALUE="Duration Type"
        OBJ_ID="47F8296F-4AF6-44CD-AE4E-93ED817FAFFA" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="0f7e36b2-a0c0-4b2f-b373-6d914428fcf9" LOCALE="es"
        MSG_ID="cluPreRequisites" MSG_VALUE="Requisitos previos"
        OBJ_ID="10f61989-7c07-47bc-80b3-4ffa6412fd79" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="0f8a013f-a6d2-4a30-9e3c-0a6464d7a22b" LOCALE="es"
        MSG_ID="cluBrief" MSG_VALUE="Escrito de la oferta"
        OBJ_ID="6ac99c90-7335-4993-99a5-6f75cb6b2c39" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="10058f78-2ce7-4aa1-bb77-215ee4490e19" LOCALE="en"
        MSG_ID="cluDurationType" MSG_VALUE="Duration Type"
        OBJ_ID="3398afb4-334d-4e87-ae4a-1f996e9e20b3" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="course"
        ID="1045a018-8fb6-45c3-b0d4-2d43e3a86319" LOCALE="en"
        MSG_ID="cluJustificationOfFees-instruct"
        MSG_VALUE="This is for internal use only and will not be seen by students."
        OBJ_ID="3d26db0d-d296-40c6-8bbe-997e9d05101e" VER_NBR="1"/>
    <KSMG_MESSAGE GRP_NAME="validation"
        ID="10863987-f792-47f5-9dc4-909b7a0e10f9" LOCALE="en"
        MSG_ID="validation.maxLengthFailed"
